db.url=jdbc:h2:mem:testdb
db.username=sa
db.password=

db.createTableSql=CREATE TABLE TestTable (id INT PRIMARY KEY, name VARCHAR(50))

db.insertSql=INSERT INTO TestTable (id, name) VALUES (1, 'Java Portability')

db.selectSql=SELECT id, name FROM TestTable